version: '3.7'

services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD:pass
      - POSTGRES_DB:db-api
      - POSTGRES_USER:user